document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("	<meta charset=\'UTF-8\'>");
document.writeln("	<title>head</title>");
document.writeln("	<style type=\'text/css\'>");
document.writeln("		body,ul,li,dl,dt { ");
document.writeln("	        padding:0; ");
document.writeln("	        margin:0; ");
document.writeln("	    }");
document.writeln("	    li {");
document.writeln("	    	list-style: none;");
document.writeln("	    }");
document.writeln("	    img { ");
document.writeln("	    	border: none;");
document.writeln("	    }");
document.writeln("	    body {");
document.writeln("	    	background: url(images/top.jpg) repeat-x;");
document.writeln("	    	width: 100%;");
document.writeln("	    	height: 80px;");
document.writeln("	    }");
document.writeln("	    .top {");
document.writeln("	    	width: 100%;");
document.writeln("			/*display: inline-block;*/");
document.writeln("	    }");
document.writeln("	    .top ul {");
document.writeln("	    	margin: 0 auto;");
document.writeln("	    	width: 90%;");
document.writeln("	    }");
document.writeln("	   .top li {");
document.writeln("	   	    float: left;");
document.writeln("	   	    line-height: 76px;");
document.writeln("	   	    font-family: \'微软雅黑\';");
document.writeln("	   	    color: #ffffff;");
document.writeln("	   	    font-size: 18px;");
document.writeln("	   	    width: 14%;");
document.writeln("	   	    text-align: center;");
document.writeln("	    }");
document.writeln("	   .top li a:visited {");
document.writeln("	    	color: #ffffff;");
document.writeln("	    }");
document.writeln("	   .top li a:link {");
document.writeln("	    	text-decoration: none;");
document.writeln("	    	color: #ffffff;");
document.writeln("	    }");
document.writeln("	   .top li a:hover { ");
document.writeln("	        text-decoration: none;");
document.writeln("	        color: #c0d8cc;");
document.writeln("	    }");
document.writeln("	   .top-Logo { ");
document.writeln("	       background: url(images/logo.png) no-repeat 2px ;");
document.writeln("	       font-size: 22px;");
document.writeln("	   }");
document.writeln("	</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("	<div class=\'top\'>");
document.writeln("	    <ul>");
document.writeln("		    <li class=\'top-Logo\'>&nbsp;</li>");
document.writeln("			<li class=\'top-HomePage\'><a href=\'index.html\'>首页</a></li>");
document.writeln("			<li class=\'top-Team\'><a href=\'member.html\'>团队介绍</a></li>");
document.writeln("			<li class=\'top-Learn\'><a href=\'LearnHome.html\'>学习家园</a></li>");
document.writeln("			<li class=\'top-Success\'><a href=\'LearnHome.html\'>成功案例</a></li>");
document.writeln("			<li class=\'top-Pretty\'><a href=\'ExcellentStar.html\'>优秀之星</a></li>");
document.writeln("			<li class=\'top-FeedBack\'><a href=\'FeedBack.html\'>意见反馈</a></li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("</body>");
document.writeln("</html>");