document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("	<meta charset=\'UTF-8\'>");
document.writeln("	<title>head</title>");
document.writeln("	<style type=\'text/css\'>");
document.writeln("		body,ul,li,dl,dt { ");
document.writeln("	        padding:0; ");
document.writeln("	        margin:0; ");
document.writeln("	    }");
document.writeln("	    li {");
document.writeln("	    	list-style: none;");
document.writeln("	    }");
document.writeln("	    img { ");
document.writeln("	    	border: none;");
document.writeln("	    }");
document.writeln("	    body {");
document.writeln("	    	background: url(images/top.jpg) no-repeat;");
document.writeln("	    	width: 100%;");
document.writeln("	    	height: 80px;");
document.writeln("	    }");
document.writeln("	    .top {");
document.writeln("	    	width: 100%;");
document.writeln("			display: inline-block;");
document.writeln("	    }");
document.writeln("	    .top ul {");
document.writeln("	    	float: left;");
document.writeln("	    	margin-left: 150px;");
document.writeln("	    }");
document.writeln("	   .top li {");
document.writeln("	   	    float: left;");
document.writeln("	   	    line-height: 76px;");
document.writeln("	   	    font-family: \'微软雅黑\';");
document.writeln("	   	    color: #ffffff;");
document.writeln("	   }");
document.writeln("	   .top li a:visited {");
document.writeln("	    	color: #ffffff;");
document.writeln("	    }");
document.writeln("	   .top li a:link {");
document.writeln("	    	text-decoration: none;");
document.writeln("	    	color: #ffffff;");
document.writeln("	    }");
document.writeln("	   .top li a:hover { ");
document.writeln("	        text-decoration: none;");
document.writeln("	        color: #c0d8cc;");
document.writeln("	    }");
document.writeln("	   .top-Logo { ");
document.writeln("	       background: ;");
document.writeln("	       font-size: 22px;");
document.writeln("	   }");
document.writeln("	   .top-HomePage {");
document.writeln("	   	    margin-left: 300px;");
document.writeln("	   }");
document.writeln("	   .top-Team {");
document.writeln("	   	    margin-left: 70px;");
document.writeln("	   }");
document.writeln("	   .top-Learn {");
document.writeln("	   	    margin-left: 70px;");
document.writeln("	   }");
document.writeln("	   .top-Pretty {");
document.writeln("	   	    margin-left: 70px;");
document.writeln("	   	}");
document.writeln("	   .top-FeedBack {");
document.writeln("	   	    margin-left: 70px;");
document.writeln("	   }");
document.writeln("	   .top-Login {");
document.writeln("	   	    margin-left: 80px;");
document.writeln("	   	    font-size: 12px;");
document.writeln("	   }");
document.writeln("	   .top-Sign {");
document.writeln("	   	    font-size: 12px;");
document.writeln("	   }");
document.writeln("	</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("	<div class=\'top\'>");
document.writeln("	    <ul>");
document.writeln("		    <li class=\'top-Logo\'>GEEK</li>");
document.writeln("			<li class=\'top-HomePage\'><a href=\'index.html\'>首页</a></li>");
document.writeln("			<li class=\'top-Team\'><a href=\'Member.html\'>团队介绍</a></li>");
document.writeln("			<li class=\'top-Learn\'><a href=\'LearnHome.html\'>学习家园</a></li>");
document.writeln("			<li class=\'top-Pretty\'><a href=\'ExcellentStar.html\'>优秀之星</a></li>");
document.writeln("			<li class=\'top-FeedBack\'><a href=\'FeedBack.html\'>意见反馈</a></li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("</body>");
document.writeln("</html>");